server:
  port: 8081
spring:
  #???????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/orca?characterEncoding=utf-8&useSSL=false
    username: root
    password: 1qaz@wsx

#mybatis?????
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.haibao.geoip.domain.model
  #??????
  configuration:
    map-underscore-to-camel-case: true

# ????????false
springfox:
  documentation:
    swagger-ui:
      enabled: true
